export const FETCH_REQUEST_MAIN = "FETCH_REQUEST_MAIN";
export const FETCH_MAIN_PHOTO_SUCCESS = "FETCH_MAIN_PHOTO_SUCCESS";
export const INCREMENT_MAIN_PHOTOS_COUNT = "INCREMENT_MAIN_PHOTOS_COUNT";
export const RESET_MAIN_PHOTOS_COUNT = "RESET_MAIN_PHOTOS_COUNT";

export const FETCH_REQUEST_SELECT = "FETCH_REQUEST_SELECT";
export const FETCH_SELECTED_PHOTO_SUCCESS = "FETCH_SELECTED_PHOTO_SUCCESS";

export const FETCH_REQUEST_ALBUM = "FETCH_REQUEST_ALBUM";
export const FETCH_ALBUM_SUCCESS = "FETCH_ALBUM_SUCCESS";
export const INCREMENT_ALBUM_PHOTOS_COUNT = "INCREMENT_ALBUM_PHOTOS_COUNT";
export const RESET_ALBUM_PHOTOS_COUNT = "RESET_ALBUM_PHOTOS_COUNT";
